### ISSUE TITLE
Document about changes to an accepted project

### ISSUE THREAD

**Issue by nikhita** [google/gsocguides#26]
The guide does not contain information about what happens in the case of changes to an accepted project. The email that is sent to mentors and org admins after the results are announced contains this information. I think it makes sense to document this in the guide.

Ref: https://developers.google.com/open-source/gsoc/2017/mentor-oa-announcements#may_2_2017_next_steps_for_all_mentors_and_org_admins

```
Changes to a Student’s Accepted Project

You and your student can decide to change the project from what was originally proposed BUT you both need to agree on the change. Neither the mentor nor the student should pressure the other person into making huge changes.

Last year we had students who were upset because they felt they couldn’t tell their mentor no. Many took on more than they could handle. In most of these cases the new project was completely different from what had been originally proposed and many students did not have the appropriate background knowledge or sometimes barely knew the particular coding language required. Be fair to your students -- set them up for success. In return they should also be flexible to change the scope of the project (within reason) if the org finds it necessary.

Students are able to edit their project title and abstract for the next month.
```

@rspier wdyt?

fyi @sttts

**Comment by rspier** [comment]
I think this makes sense to include.  I don't think the exact text from the email is right.  Send a PR with a proposed change?

**Comment by nikhita** [comment]
> Send a PR with a proposed change?

Sure :+1:
