### ISSUE TITLE
To update "Staying Engaged with Your Community"

### ISSUE THREAD

**Issue by ManishAradwad** [google/gsocguides#44]
[https://google.github.io/gsocguides/student/staying-engaged-with-your-community.html](url)
Under "Next Summer" topic , applying again as a student next summer is mentioned.
Is it right?? cause I think the rule says that previously accepted GSoC student cannot apply again

![Screenshot from 2019-12-12 04-43-30](https://user-images.githubusercontent.com/29497701/70668570-01440e00-1c9a-11ea-89fb-5b3e28812cf1.png)

**Comment by rspier** [comment]
As of the 2019 contest, the rules says you can be accepted to participate up to 2 times.  So some students can apply again, if they've only been accepted once.
