### ISSUE TITLE
Updating the content of gsocguides

### ISSUE THREAD

**Issue by ShubhamPalriwala** [google/gsocguides#54]
The current version of the website is around 10 years old.
The copyright is also of 2009 and all the quotes are of GSOC students till 2010.
Shouldn't the data be revamped before this year's GSOC at least ?
https://google.github.io/gsocguides/#

**Comment by rspier** [comment]
The copyright references the year of initial creation.  The guidance we receive is that it is not necessary to update the copyright year every time the content changes.

The content is reviewed and updated periodically.
