### ISSUE TITLE
Logo in header not large enough

### ISSUE THREAD

**Issue by himanshu007-creator** [google/gsocguides#56]
The logo is quite small and it doesn't come to notice. I feel , there is a need of increasing size of this logo
![2021-02-17 (2)](https://user-images.githubusercontent.com/65963997/108157820-a44baf80-7109-11eb-8335-582621e2bfb5.png)

**Comment by 24shreya** [comment]
I completely agree. 
Try changing dimensions of image by simply using height and width attribute in img src tag
<img src ="/gsocguides/images/sun-small.png" style="width:30px;height:30px;">

Or using another image of higher resolution so that the dimensions can be flexible.

**Comment by rspier** [comment]
Closing as WillNotFix.

I don't disagree that the logo is subtle in the current design, but it's not a priority to fix *just* the logo size right now.  Improvements to the overall look and feel might be interesting, but not going to hold the bug open for it.
